// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCTIKIyi_1oDxoBFnLobNV-QTJEt5TC100',
    appId: '1:329921756016:web:a9492876b99074d4606db5',
    messagingSenderId: '329921756016',
    projectId: 'soltech-clone',
    authDomain: 'soltech-clone.firebaseapp.com',
    databaseURL: 'https://soltech-clone-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'soltech-clone.firebasestorage.app',
    measurementId: 'G-5KR6WE0CXX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBRhgFGsnf_YvaL6-zq_hJevUrggKmuQHM',
    appId: '1:329921756016:android:9650f98d9b4554f2606db5',
    messagingSenderId: '329921756016',
    projectId: 'soltech-clone',
    databaseURL: 'https://soltech-clone-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'soltech-clone.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAn97txaKbxInjwJtfvWYy1pI4YtcIX_Ds',
    appId: '1:329921756016:ios:377ea5f4046e861f606db5',
    messagingSenderId: '329921756016',
    projectId: 'soltech-clone',
    databaseURL: 'https://soltech-clone-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'soltech-clone.firebasestorage.app',
    iosBundleId: 'com.example.soltechApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAn97txaKbxInjwJtfvWYy1pI4YtcIX_Ds',
    appId: '1:329921756016:ios:377ea5f4046e861f606db5',
    messagingSenderId: '329921756016',
    projectId: 'soltech-clone',
    databaseURL: 'https://soltech-clone-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'soltech-clone.firebasestorage.app',
    iosBundleId: 'com.example.soltechApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCTIKIyi_1oDxoBFnLobNV-QTJEt5TC100',
    appId: '1:329921756016:web:02863a2bd6d6b403606db5',
    messagingSenderId: '329921756016',
    projectId: 'soltech-clone',
    authDomain: 'soltech-clone.firebaseapp.com',
    databaseURL: 'https://soltech-clone-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'soltech-clone.firebasestorage.app',
    measurementId: 'G-ZFVTH19SDE',
  );

}
